name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./

      - name: Deploy
        run: |
          export OPENAI_API_KEY=$OPENAI_API_KEY
          streamlit run test.py  # Replace with the actual command to run your Streamlit app
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        working-directory: ./
