name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Choose an appropriate runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Use the desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./  # Adjust to the path where your code is

      - name: Deploy
        run: |
          export OPENAI_API_KEY=$OPENAI_API_KEY  # Set the API key as an environment variable
          streamlit run your_app.py  # Replace with the actual command to run your Streamlit app
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        working-directory: ./  # Adjust to the path where your code is
